keys:
  - &users:
    - &primary age10pzhycy2vu2putmw4agnrhs9r9p5ud6ck9vv95z2d2uc6mcuze2qzv5ezw
  - &hosts:
    - &vega age1rqjwxhvm33774ttkwynj3h2wpkuwwn679ma5qar6qdwctzqq8gxscf0khz
    - &homelab age1e7wg8eed0csfjt6jsa56rpyhpwsuxusly9yj8gdz555zsgf8z45q6c4jup
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
        - *primary
        - *vega
        - *homelab
